# Generated by Django 3.0.8 on 2020-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trigrams',
            field=models.TextField(blank=True),
        ),
    ]
